---
# Config file for automatic testing at travis-ci.org

language: python

dist: xenial

python:
  - "3.6"
  - "3.7"

# sudo false implies containerized builds
sudo: false

# Notify by email when build results changes
notifications:
  email: change

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      install:
          - pip install pre-commit
          - pre-commit install-hooks
      script:
          - pre-commit run --all-files

    - stage: test
      install:
          - pip install .
          - pip install pytest pytest-coverage coveralls
      script:
          - pytest -ra --cov=pandas_utility tests
          - coverage report -m
          - coveralls
