---
# Config file for automatic testing at travis-ci.org

language: python

dist: bionic

python:
  - 3.6

# sudo false implies containerized builds
sudo: false

# Notify by email when build results changes
notifications:
  email: change

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      before_install:
          - pip install pre-commit
      install:
          - pre-commit install-hooks
      script:
          - pre-commit run --all-files

    - stage: test
      before_install:
          - pip install -U .
      install:
          - pip install pytest pytest-coverage coveralls
      script:
          - pytest -ra --cov=pandas_utility tests
          - coverage report -m
          # - coveralls
